version: '3.4'

services:
  avaliacao.microservice.webapi:
    image: ${DOCKER_REGISTRY-}avaliacaomicroservicewebapi
    container_name: avaliacao.microservice.webapi
    build:
      context: .
      dockerfile: CarroController/Dockerfile
    ports: ['5000:80','5001:443']
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lucas
      POSTGRES_DB: veiculos
    volumes:
      - avaliacao.microservice.database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  avaliacao.microservice.database:
